version: "3"
services:
    app:
        build: .
        depends_on:
            - db
        restart: always
        volumes:
            - app:/var/www
            - ./docker/permission.sh:/var/www/permission.sh
    nginx:
        image: nginx:1.13
        depends_on:
            - app
        links:
            - app
        ports:
            - 8083:80
        restart: always
        volumes:
            - app:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    db:
        image: mariadb:latest
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        restart: always
        volumes:
            - db-data:/var/lib/mysql
volumes:
    app:
    db-data:
        driver: local
