version: "3"
services:
    app:
        build: ./php7-fpm
        depends_on:
            - db
        restart: always
        volumes:
            - ./app/:/var/www
            - ./permission.sh:/var/www/permission.sh
    nginx:
        image: nginx:1.13
        depends_on:
            - app
        ports:
            - 80:80
        restart: always
        volumes:
            - ./app/:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    db:
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: always
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
        driver: local
